apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app
spec:
  replicas: 1  # Single replica for local testing
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
      annotations:
        prometheus.io/scrape: "true"  # Enable Prometheus scraping
    spec:
      containers:
      - name: weather-app
        image: bibek87/dynamic_weather_app:latest
        ports:
        - containerPort: 5000
        env:
        - name: OPENWEATHER_API_KEY
          valueFrom:
            secretKeyRef:
              name: weather-secrets
              key: api-key
